# Scraping
Data scraping was performed by collecting user review data of the "Identitas Kependudukan Digital" application from the Google Play Store with the help of the google-play-scraper library. The data collected includes the reviewer's name, the star rating given, the time the review was submitted, and the content of the review.

### Library Installation

In [2]:
%pip install google-play-scraper

Requirement already satisfied: google-play-scraper in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (1.2.7)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Import Library

In [3]:
from google_play_scraper import app # type: ignore
import pandas as pd # type: ignore
import numpy as np # type: ignore
from google_play_scraper import Sort, reviews # type: ignore
from pathlib import Path

In [4]:
# function for saving dataframe result of scrapping to csv file
def makeCsv(fileName):
    filepath = Path(f'dataset/{fileName}')  
    filepath.parent.mkdir(parents=True, exist_ok=True)  
    df.to_csv(filepath) # type: ignore

In [6]:
# importing the google_play_scraper library to access reviews and app information from the Google Play Store.
from google_play_scraper import app, reviews_all, Sort

# Retrieving all reviews from the app with the ID 'gov.dukcapil.mobile_id' on the Google PlayStore.
# The scraping process may take some time depending on the number of reviews available.
scrapreview = reviews_all(
    'gov.dukcapil.mobile_id',
    lang='id', 
    country='id', 
    sort=Sort.MOST_RELEVANT, 
    count=2000, 
)

In [14]:
# Creating a DataFrame from scrapreview results
app_reviews_df = pd.DataFrame(np.array(scrapreview),columns=['review'])
app_reviews_df = app_reviews_df.join(pd.DataFrame(app_reviews_df.pop('review').tolist()))

app_reviews_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,c1c4b362-888e-4939-84dd-ab9f8fc918eb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Sekarang tidak bisa di buka,selalu kesalahan k...",5,235,1.2.2,2024-07-04 12:30:42,None,NaT,1.2.2
1,686e43c1-3d35-46ba-974a-8c4b4946e6a0,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi nya ""terjadi kesalahan koneksi"" ,suda...",1,532,1.2.2,2024-05-02 09:41:54,None,NaT,1.2.2
2,fd30e08d-3859-4c82-8a91-f8ba9c846256,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi tidak responsif, berjalan lambat, res...",2,622,1.2.2,2024-05-15 15:20:22,None,NaT,1.2.2
3,4abb1bdf-18f9-4afe-848f-481ffe926e62,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Apasih gunanya E-KTP tapi gak bisa cetak KTP-n...,1,616,1.2.2,2024-05-01 08:41:45,None,NaT,1.2.2
4,e3898f2f-bdf6-4dc0-bc08-a752f0fdaf8c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aku kasih bintang 3 karna mau masuk aja harus ...,3,103,1.2.2,2024-05-13 13:41:13,None,NaT,1.2.2
...,...,...,...,...,...,...,...,...,...,...,...
23308,69c10cc5-ec1f-4075-a0cb-b1c2bc0f068a,Nuki Arya,https://play-lh.googleusercontent.com/a/ACg8oc...,👍,5,0,None,2024-02-22 06:58:40,None,NaT,None
23309,89916c94-259c-4d55-86a8-dbed4c95e510,Adeka Mustofa,https://play-lh.googleusercontent.com/a-/ALV-U...,Mantap💪💪💪💪,5,0,None,2023-03-06 11:28:02,None,NaT,None
23310,68627649-0779-4704-8e7e-16508cc8870e,Irpay Albantani,https://play-lh.googleusercontent.com/a-/ALV-U...,Oc..,5,0,None,2022-09-21 22:04:08,None,NaT,None
23311,4223d472-8694-434b-af0f-ca8861454bd5,Riza Agoesdy,https://play-lh.googleusercontent.com/a/ACg8oc...,mantap....,5,0,None,2022-06-20 12:55:12,None,NaT,None
23312,9eefa338-a005-4e64-babd-83098adbe418,ファーミ,https://play-lh.googleusercontent.com/a-/ALV-U...,🤣,1,0,None,2024-06-11 08:17:02,None,NaT,None

In [15]:
# Count the number of rows and columns in a DataFrame
jumlah_review, jumlah_kolom = app_reviews_df.shape

# Display the first five rows of the DataFrame app_reviews_df
app_reviews_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,c1c4b362-888e-4939-84dd-ab9f8fc918eb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Sekarang tidak bisa di buka,selalu kesalahan k...",5,235,1.2.2,2024-07-04 12:30:42,None,NaT,1.2.2
1,686e43c1-3d35-46ba-974a-8c4b4946e6a0,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi nya ""terjadi kesalahan koneksi"" ,suda...",1,532,1.2.2,2024-05-02 09:41:54,None,NaT,1.2.2
2,fd30e08d-3859-4c82-8a91-f8ba9c846256,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi tidak responsif, berjalan lambat, res...",2,622,1.2.2,2024-05-15 15:20:22,None,NaT,1.2.2
3,4abb1bdf-18f9-4afe-848f-481ffe926e62,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Apasih gunanya E-KTP tapi gak bisa cetak KTP-n...,1,616,1.2.2,2024-05-01 08:41:45,None,NaT,1.2.2
4,e3898f2f-bdf6-4dc0-bc08-a752f0fdaf8c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aku kasih bintang 3 karna mau masuk aja harus ...,3,103,1.2.2,2024-05-13 13:41:13,None,NaT,1.2.2

In [16]:
# Display information about the DataFrame app_reviews_df
app_reviews_df.info() # type: ignore

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23313 entries, 0 to 23312
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              23313 non-null  object
 1   userName              23313 non-null  object
 2   userImage             23313 non-null  object
 3   content               23313 non-null  object
 4   score                 23313 non-null  int64
 5   thumbsUpCount         23313 non-null  int64
 6   reviewCreatedVersion  19522 non-null  object
 7   at                    23313 non-null  datetime64[ns]
 8   replyContent          2 non-null      object
 9   repliedAt             2 non-null      datetime64[ns]
 10  appVersion            19522 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 2.0+ MB

In [17]:
# Create a new DataFrame (clean_df) by removing rows that have missing values ​​(NaN) from app_reviews_df
clean_df = app_reviews_df.dropna() # type: ignore

In [18]:
# Displays information about the DataFrame clean_df after cleaning missing values ​​(NaN)
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 12782 to 21049
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              2 non-null      object
 1   userName              2 non-null      object
 2   userImage             2 non-null      object
 3   content               2 non-null      object
 4   score                 2 non-null      int64
 5   thumbsUpCount         2 non-null      int64
 6   reviewCreatedVersion  2 non-null      object
 7   at                    2 non-null      datetime64[ns]
 8   replyContent          2 non-null      object
 9   repliedAt             2 non-null      datetime64[ns]
 10  appVersion            2 non-null      object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 192.0+ bytes

In [19]:
# Remove duplicate rows from DataFrame clean_df
clean_df = clean_df.drop_duplicates()

# Calculate the number of rows and columns in DataFrame clean_df after removing duplicates
number_of_reviews_after_removing_duplicates, number_of_columns_after_removing_duplicates = clean_df.shape

In [21]:
# Displays information about the DataFrame clean_df after removing duplicates
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 12782 to 21049
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              2 non-null      object
 1   userName              2 non-null      object
 2   userImage             2 non-null      object
 3   content               2 non-null      object
 4   score                 2 non-null      int64
 5   thumbsUpCount         2 non-null      int64
 6   reviewCreatedVersion  2 non-null      object
 7   at                    2 non-null      datetime64[ns]
 8   replyContent          2 non-null      object
 9   repliedAt             2 non-null      datetime64[ns]
 10  appVersion            2 non-null      object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 192.0+ bytes

### Download As CSV

In [20]:
makeCsv('dataset-dukcapilApp.csv')